# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170923_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[(0, 'Новый'), (1, 'Активный'), (2, 'Завершен')], default=0, max_length=255, verbose_name='Status'),
        ),
    ]
